name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y git zip unzip wget openjdk-17-jdk build-essential
        pip install --upgrade pip
        pip install cython buildozer

    - name: Nuke old buildozer SDK
      run: |
        rm -rf ~/.buildozer/android/platform/android-sdk

    - name: Setup Android SDK (manual)
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT

        cd $HOME

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip

        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        unzip -q cmdline.zip -d $ANDROID_SDK_ROOT/cmdline-tools

        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools"
        sdkmanager "platforms;android-31"
        sdkmanager "build-tools;34.0.0"

    - name: Force env
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk