name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # 🔥 QUAN TRỌNG: dùng docker buildozer ổn định nhất
    container:
      image: kivy/buildozer:latest

    env:
      BUILDOZER_ALLOW_ROOT: 1
      PYTHONUNBUFFERED: 1

    steps:
    # ========================
    # CHECKOUT CODE
    # ========================
    - name: Checkout code
      uses: actions/checkout@v4

    # ========================
    # CHECK ENV
    # ========================
    - name: Show environment
      run: |
        python --version
        buildozer --version

    # ========================
    # CLEAN CACHE
    # ========================
    - name: Clean build folders
      run: |
        rm -rf .buildozer
        rm -rf bin

    # ========================
    # BUILD APK
    # ========================
    - name: Build APK
      run: |
        buildozer -v android debug

    # ========================
    # UPLOAD APK
    # ========================
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk